api:
  dashboard: false

entryPoints:
  internal:
    address: ':8081'
  public:
    address: ':8080'

log:
  format: json
  level: WARN

ping:
  entryPoint: public

providers:
  file:
    filename: /etc/traefik/routes.yaml
    watch: false
