services:
  api-1:
    build:
      dockerfile: infra/realtime/Dockerfile.test-api
    environment:
      KOVCHEG_IDENTITY_STUB_ENABLED: 'true'
      NODE_ENV: test

  api-2:
    build:
      dockerfile: infra/realtime/Dockerfile.test-api
    environment:
      KOVCHEG_IDENTITY_STUB_ENABLED: 'true'
      NODE_ENV: test
